name: requirements

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  check-skip:
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.skip-check.outputs.should-skip }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: skip-check
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if echo "$COMMIT_MSG" | grep -qiE "skip-ci|skip-lint"; then
            echo "should-skip=true" >> $GITHUB_OUTPUT
          else
            echo "should-skip=false" >> $GITHUB_OUTPUT
          fi


  security-checks:
    runs-on: ubuntu-latest
    steps:
      #Clonacion y checkeo del proyecto
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      #Analisis de informacion sensible
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.67.5
        with:
          extra_args: --only-verified

  lint:
    needs: check-skip
    if: needs.check-skip.outputs.should-skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'master'
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - run: git branch -a

      - run: pnpm exec eslint --config eslint.config.cjs 

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        with:
          args: >
            -Dsonar.organization=ocmi-test
            -Dsonar.projectKey=ocmi-test
            -Dsonar.branch.name=main
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=src
            -Dsonar.language=ts 
            -Dsonar.login=${{ secrets.SONAR_CLOUD_TOKEN }} 
            -Dsonar.exclusions=**/node_modules/**,**/*.test.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.typescript.tsconfigPath=tsconfig.json
            -Dsonar.exclusions=apps/**,dist/**,packages/**,lib/**,public/**,node_modules/**

  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Cache Sonar
        uses: actions/cache@v3
        id: cache-sonar
        with:
          path: node_modules/.cache/sonar
          key: source-${{ github.event.repository.name }}-${{ hashFiles('**') }}
      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=ocmi-test \
            -Dsonar.organization=ocmi-test \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.branch.name=main \
            -Dsonar.login=${{ secrets.SONAR_CLOUD_TOKEN }} \
            -Dsonar.sources=src \
            -Dsonar.language=ts \
            -Dsonar.exclusions=apps/**,dist/**,packages/**,lib/**,public/**,node_modules/** \

#   security:
#     name: Security Checks (OWASP)
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Run OWASP Dependency Check
#         uses: dependency-check/Dependency-Check_Action@main
#         with:
#           project: "Playwright Security Scan"
#           scanpath: "."
#           format: "HTML"
#           outdir: "./reports"
#       - name: Upload OWASP Report
#         uses: actions/upload-artifact@v4
#         with:
#           name: security-report
#           path: ./reports

#   typecheck:
#     name: TypeScript Type Check
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: pnpm/action-setup@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: 'pnpm'
#       - run: pnpm install --frozen-lockfile
#       - name: Run TypeScript Type Check
#         run: pnpm exec tsc --noEmit