name: Continuous testing security

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment of Github Actions"
        required: false
        default: ""
        type: string
      repository:
        description: "Name of repo in Github"
        required: true
        type: string
      target-url-zap:
        description: "URL to scan in OWASP ZAP (for web security tests)"
        required: false
        default: ''
        type: string
      path-app:
        description: "Path of APK/IPA to scan in MobSF (for mobile security tests)"
        required: false
        default: ''
        type: string
    secrets:
      DIG_READER_GITHUB_ACCESS_TOKEN:
        required: true

permissions:
  id-token: write
  contents: read   

jobs:
  security-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Validate type security test
        env:
          PATH_APP: ${{ inputs.path-app }}
          TARGET_ZAP: ${{ inputs.target-url-zap }}
        run: |
          if [ -z "$PATH_APP" ] && [ -z "$TARGET_ZAP" ]; then
            echo "Debe usar la variable path-app (para apps móviles) o target-url-zap (para web)."
            exit 1
          fi

      # 🔹 Evaluate Mobile Apps Security (MobSF)
      - name: Checkout automation project
        if: ${{ inputs.path-app != '' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          token: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
          persist-credentials: false
          path: ./${{ inputs.repository }}

      - name: Run MobSF Scan
        if: ${{ inputs.path-app != '' }}
        uses: ./.github/actions/bbog-dig-cat-action-mobsf-pipeline
        with:
          INPUT_APP_NAME: ${{ inputs.repository }}/${{ inputs.path-app }}
          OUTPUT_FILE_NAME: report_json.json

      - name: Upload MobSF Report
        if: ${{ inputs.path-app != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: security_reports
          retention-days: 1
          path: report_json.json

      # 🔹 Evaluate Web Apps Security (OWASP ZAP)
      - name: ZAP baseline scan
        if: ${{ inputs.target-url-zap != '' }}
        uses: zaproxy/action-baseline@v0.14.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:20240103-stable'
          target: ${{ inputs.target-url-zap }}
          token: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
          allow_issue_writing: false
          artifact_name: security_reports

      - name: Restore security report
        if: ${{ always() }}
        uses: actions/download-artifact@v4
        with:
          name: security_reports
          path: ${{ inputs.repository }}/security-reports